### ISSUE TITLE
Can't enter Parkour Warrior Dojo

### ISSUE THREAD

**Issue by F2PAlius** [danielml2/mcci-stats-tracker#1]
Even though it doesn't track Dojo, I keep crashing when trying to enter the Daily Challenge to do quests.

**Comment by danielml2** [comment]
Hi, I'll try to replicate it myself, but can you specify which version of the mod are you using (Mod version & Minecraft version)?

Also, please send the log file with the crash, these should be found in the game directory (%appdata% for windows) under logs, without the log file it would be a lot harder for me to fix it (if i can't replicate the issue myself)

**Comment by danielml2** [comment]
Okay I've re-produced the issue, and implemented a fix, just testing it now making sure it doesn't break anything and it should be good to go

**Comment by danielml2** [comment]
Issue is fixed, tomorrow i'll upload the fixed versions as 0.1.2
