### ISSUE TITLE
(Feature Request) Toggleable HUD

### ISSUE THREAD

**Issue by JTModel3** [danielml2/mcci-stats-tracker#2]
Is it possible to make the hud in games toggleable?

**Comment by danielml2** [comment]
Yes! 
It's actually coming in the 0.2 update which is almost done, which two major UI customizations: where it renders & text color (or if to render the HUD at all)

Or do you mean something more along the lines of a keybind that disables it momentairly?

**Comment by danielml2** [comment]
Fixed in [0.2](https://github.com/danielml2/mcci-stats-tracker/releases/tag/0.2)

Includes a keybind to disable it momentairly while held, and the option to disable the hud entirely while still tracking the stats in the background
