### ISSUE TITLE
0.2.2 crash when joining MCCI [bug]

### ISSUE THREAD

**Issue by osfanbuff63** [danielml2/mcci-stats-tracker#5]
**Describe the bug**
The mod crashes the game

**To Reproduce**
1. Try and join MCCI with this mod (on 1.20.2)
2. Notice the crash

**Expected behavior**
The game to let me join MCCI.

**Log file**
https://mclo.gs/cXLioTx

**Mod Setup**
 - Minecraft version: 1.20.2
 - Fabric API Version: 0.90.7+1.20.2
- Fabric Loader version: 0.14.22
 - Mod version: 0.2.1
- Other mods (Especially any mod that might modify message or scoreboard behaviour): None

**Comment by osfanbuff63** [comment]
Of note, on Modrinth it says the mod is compatible with 1.20.2 but on GitHub it doesn't.

**Comment by danielml2** [comment]
Yeah, that's my error with the modrinth version the mod isn't officially supported yet to 1.20.**2**, i'll fix the modrinth post
not sure when i'd update it, but shouldn't be too bad

**Comment by danielml2** [comment]
probably irrelevant with now 0.2.3 being 1.20.4 so yeah
